### ISSUE TITLE
Remove rebel.xml from deployed artifact

### ISSUE THREAD

**Issue by heruan** [vaadin-component-factory/vcf-noscroll-grid#2]
The JAR artifact that has been deployed for this component version 2.0.1 includes a `rebel.xml` file, which causes conflicts with existing JRebel installation.

Please redeploy the artifact without the `rebel.xml` file.

**Comment by TatuLund** [comment]
I made today v1.0.3 and v2.0.2. Atleast there is was no rebel.xml in myworkspace when I did the new builds. So I aassume this should be fixed now.
