### ISSUE TITLE
NoScrollGrid with row Details when rows are less then container height (no scrollbar problem)

### ISSUE THREAD

**Issue by darmro** [vaadin-component-factory/vcf-noscroll-grid#3]
Hi,

**Environment:**  
Vaadin 14.4.6, pure java 8.

**Problem:**
NoScrollGrid has a big problem when rows have item details component and there are few rows only in the grid, ie. when the grid initially has less height then container height (container in which grid is attached and which supports external scrollbar for grid). **In this situation there's initially no scrollbar on target scroll container** (no needed because all rows are visible in the grid). But lack of the scrollbar is a big problem when one expands item details for some row because scrollbar doesn't appear even when details component will take up a lot of space in the grid. In that case, the rows below are not visible and there's no way to scroll down to them unless you hide the item details.

I've prepared test case (from vaadin skeleton starter app):
[skeleton-starter-flow-14.zip](https://github.com/vaadin-component-factory/vcf-noscroll-grid/files/5875335/skeleton-starter-flow-14.zip)

Just run it, open in desktop browser with full page, and click in a grid row to open details. 
When there're more rows in the grid and scrollbar initially is visiblee there's no problem because even when you open item details you can scroll down to see bottom rows. In that case the grid have some extra height buffered to support external scrolling. See screenshots below.

**Screenshots:**
Initial page with 5 rows in the grid (no scrollbar in external container):
![image](https://user-images.githubusercontent.com/56316289/105891755-47307280-6011-11eb-9e9c-b6fdf3c58e19.png)

When you open item details (still no scrollbar so you can't scroll to bottom rows):
![image](https://user-images.githubusercontent.com/56316289/105892026-95457600-6011-11eb-801a-05fc65ea8561.png)

Initial page with 100 rows in the grid (scrollbar in external container is present!):
![image](https://user-images.githubusercontent.com/56316289/105892097-aa220980-6011-11eb-92ca-7a4d2fbc7164.png)

When you open item details (scrollbar is present so you can scroll to bottom rows):
![image](https://user-images.githubusercontent.com/56316289/105892155-bc9c4300-6011-11eb-9f31-e3e57e0f8152.png)

**Question:**
Is this a bug? 
I've found a workaround for this- I've just overrided NoScrollGrid class and its setDetailsVisible method:
```
    @Override
    public void setDetailsVisible(E item, boolean visible) {
        super.setDetailsVisible(item, visible);
        getElement().callJsFunction("resetHeight");  
    }
```
But there's a problem with this idea. After opening details (calling reseHeight js function) scroll on container goes up to the beginning (when grid has a lot of rows it's a big problem).
Any other idea? :)

**Comment by tltv** [comment]
Fixed in version 2.0.4.
