### ISSUE TITLE
NoScrollGrid for Vaadin 18+

### ISSUE THREAD

**Issue by darmro** [vaadin-component-factory/vcf-noscroll-grid#4]
In Vaadin 19.0.0.beta4 there are few issues possibly due to not being  compatible with new Grid version in Vaadin 18+ (there were a lot of changes from Vaadin 14).
These issueas are for example:
1) (TypeError) : $0.setRowsShownMoreOnScrollToBottom is not a function (in FlowClient.js)
2) (TypeError) : $0.setShowMoreOnScrollToBottom is not a function (in FlowClient.js)
3) (TypeError) : Cannot read property 'GridElement' of undefined (in noscroll-grid.js)
4) and mainly- scroll container doesn't work at all- scrollbar is in the main Grid

Is there any chance to upgrade this very nice and usefull component? :)

**Comment by jcgueriaud1** [comment]
Unfortunately the component has been done for Vaadin 14. I've updated the description in the Vaadin directory (from 14+ to 14).

I don't know the effort.

**Comment by darmro** [comment]
It is very nice and usefull component :)  What kind of paid support do we need to have this component upraded to V19? :)

**Comment by jcgueriaud1** [comment]
Hi,

If you are a Prime customer you can contact us on the Expert Chat: https://vaadin.com/pro/expert-chat

If not, you can send us an email at sales@vaadin.com

**Comment by tltv** [comment]
New released version 3.0.0 adds support for Vaadin 19.
